# Generated by Django 4.2 on 2023-06-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
